### ISSUE TITLE
Notification on top

### ISSUE THREAD

**Issue by anuraag488** [itsdrnoob/DataMonitor#116]
Hi
Currently notification doesn't stay on top. I think if you use [setSortKey(0)](https://developer.android.com/reference/android/app/Notification.Builder#setSortKey(java.lang.String)) then notification will stay on top.

**Comment by anuraag488** [comment]
@itsdrnoob Notification still doesn't stay on top on 2.3.0 beta 1. Can you give a try to above method?

**Comment by itsdrnoob** [comment]
Well according to the docs:
> `setSortKey()`
Set a sort key that orders this notification among other notifications from the same package.

So I'm not sure if it'll have any effect when there are notifications from multiple packages.
Even with max priority, I'm not seeing the expected behaviour. Still trying to figure out a way.

**Comment by anuraag488** [comment]
It's been used by other speed meter app and i have tested it using Tasker.

**Comment by itsdrnoob** [comment]
If that's the case, I'll give it a shot.
