### ISSUE TITLE
App not listed in settings for alarm permission

### ISSUE THREAD

**Issue by clayb91** [itsdrnoob/DataMonitor#228]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

2.4.0

### Steps to reproduce the bug

1. Install app
2. App requests alarm permission and takes you to settings
3. Data Monitor not listed in the menu to grant alarm permissions

### Expected behavior

App appears in list to be granted alarm permissions 

### Actual behavior

App not listed

### Screenshots/Screen recordings

![Screenshot_20240111-121658](https://github.com/itsdrnoob/DataMonitor/assets/65564355/6bd0f356-fbbc-4053-b989-70ce671df2f0)

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 7 Pro

**Comment by itsdrnoob** [comment]
Turns out, this is the intended behaviour. If the app is exempted from battery optimisation, it won't show up in _Alarms & reminders_ settings as the permission is allowed by default.

If you enable battery optimisation for the app, you can see it gets listed again.
![photo_2024-04-30 21 23 34](https://github.com/itsdrnoob/DataMonitor/assets/52557407/0a430855-ed31-4d22-9361-ccdec6d0b908)
