### ISSUE TITLE
Hindi translation complete 

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#88]
I asked one of my Indian friend to translate the app but he only could translate 99% he is currently lacking context in following string

mailto:%1$s?&subject=%2$s&body=%3$s

Which parts of this needs to be translated?could you provide some context? Is mailto can be considered as "mail to" for translation.?

**Comment by AxusWizix** [comment]
> I asked one of my Indian friend to translate the app but he only could translate 99% he is currently lacking context in following string
> 
> mailto:%1$s?&subject=%2$s&body=%3$s
> 
> Which parts of this needs to be translated?could you provide some context? Is mailto can be considered as "mail to" for translation.?

[Master2050](https://github.com/Master2050), The line containing ''**mailto:%1$s?&subject=%2$s&body=%3$s**'' must not be translated, otherwise there will be an error.
To understand what this line is: &quot;&lt;a href=&quot;**mailto:test@test.com?subject=Subject&amp;body=Text message**&quot;&gt;Send a letter&lt;/a&gt;&quot;

**Comment by itsdrnoob** [comment]
@AxusWizix is right, I'll mark it as untranslatable.

**Comment by killerrook** [comment]
It still can be translated i said him to copy paste the same.
